### ISSUE TITLE
SIGILL: illegal instruction panic

### ISSUE THREAD

**Issue by archever** [cloudwego/base64x#7]
**Describe the bug**

enconter a panic, when hertz bind a base64 json struct. 
it happened in specific machine

**Screenshots**

```go
06/26 13:01:26.561776 engine.go:389: [Info] HERTZ: Using network library=netpoll
2024/06/26 13:01:26.563355 transport.go:109: [Info] HERTZ: HTTP server listening on address=[::]:6789
SIGILL: illegal instruction
PC=0x7f93b04fe9d6 m=7 sigcode=2
instruction bytes: 0xc5 0xf8 0x77 0xc3 0x48 0x8b 0x45 0xa8 0x4c 0x29 0xf8 0x48 0x29 0xc8 0xe9 0xdf

goroutine 1617 [running]:
_b64decode()
        base64x/native.c:1 +0x44a6 fp=0xc000e9aa78 sp=0xc000e9aa70 pc=0x7f93b04fe9d6
decode_()
        ?:0 +0x1130 fp=0xc000e9ab98 sp=0xc000e9aa78 pc=0x7f93b0475130
[github.com/bytedance/sonic/internal/decoder.decodeTypedPointer](http://github.com/bytedance/sonic/internal/decoder.decodeTypedPointer)({0xc001439800, 0x3747}, 0xc001415500?, 0x2d9ab60?, 0x0?, 0xc000e9acc0?, 0x40f82a?)
        /go/pkg/mod/[github.com/bytedance/sonic@v1.11.2/internal/decoder/primitives.go:34](http://github.com/bytedance/sonic@v1.11.2/internal/decoder/primitives.go:34) +0xdb fp=0xc000e9ac30 sp=0xc000e9ab98 pc=0x23ccadb
[github.com/bytedance/sonic/internal/decoder.(*Decoder).Decode](http://github.com/bytedance/sonic/internal/decoder.(*Decoder).Decode)(0xc00144e2a0, {0x2e7edc0?, 0xc00141d830})
        /go/pkg/mod/[github.com/bytedance/sonic@v1.11.2/internal/decoder/decoder.go:142](http://github.com/bytedance/sonic@v1.11.2/internal/decoder/decoder.go:142) +0x25b fp=0xc000e9ad18 sp=0xc000e9ac30 pc=0x23b8a5b
[github.com/bytedance/sonic.frozenConfig.UnmarshalFromString](http://github.com/bytedance/sonic.frozenConfig.UnmarshalFromString)({{0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, ...}, ...}, ...)
        /go/pkg/mod/[github.com/bytedance/sonic@v1.11.2/sonic.go:107](http://github.com/bytedance/sonic@v1.11.2/sonic.go:107) +0x52 fp=0xc000e9ad48 sp=0xc000e9ad18 pc=0x23d44b2
[github.com/bytedance/sonic.frozenConfig.Unmarshal(...)](http://github.com/bytedance/sonic.frozenConfig.Unmarshal(...))
        /go/pkg/mod/[github.com/bytedance/sonic@v1.11.2/sonic.go:119](http://github.com/bytedance/sonic@v1.11.2/sonic.go:119)
[github.com/bytedance/sonic.(*frozenConfig).Unmarshal](http://github.com/bytedance/sonic.(*frozenConfig).Unmarshal)(0x28?, {0xc001436000?, 0x40f801?, 0xc000e9ae60?}, {0x2e7edc0?, 0xc00141d830?})
        <autogenerated>:1 +0x95 fp=0xc000e9adb8 sp=0xc000e9ad48 pc=0x23d4ef5
[github.com/bytedance/sonic.API.Unmarshal-fm](http://github.com/bytedance/sonic.API.Unmarshal-fm)({0xc001436000?, 0x186fae6?, 0xc0014223c0?}, {0x2e7edc0?, 0xc00141d830?})
```

**Kitex version:**

sonic: v1.11.2

**Environment:**

go v1.21

**Additional context**

cpu info:
```
processor       : 1
vendor_id       : GenuineIntel
cpu family      : 15
model           : 6
model name      : Intel(R) Xeon(R) Silver 4316 CPU @ 2.30GHz
stepping        : 3
microcode       : 0x1
cpu MHz         : 2294.608
cache size      : 16384 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic aes hypervisor lahf_lm cpuid_fault pti
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips        : 4589.21
clflush size    : 64
cache_alignment : 128
address sizes   : 46 bits physical, 48 bits virtual
```

**Comment by AsterDY** [comment]
the lease cpu set must be sse4, your CPU is too old
